on:
  workflow_dispatch:

jobs:
  scheduled-data-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: pip-install deps
        run: pip install -r tools/env/python-deps.txt
      - name: auto-update.sh
        run: bash auto-update.sh
